book/urls.py
from django.urls import path
from .views import *

app_name = 'book'

urlpatterns = [
    path('', books, name='book'),
    path('book/<int:year>/<int:month>/<int:day>/<slug:slug>/', BookList.as_view(), name='book_details'),
    path('book/add/', book_create, name='book_create'),
    path('book/update/<int:pk>/', book_update, name='book_update'),
    path('book/delete/<int:pk>p/', delete, name='delete'),
    path('signup/', signup, name='signup'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('user/<str:username>/books/', user_books, name='user_books'),
    path('emailsent/', postdate, name='send_email'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book.urls')),
]

book/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone

class Book(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique_for_date='publish')
    author = models.CharField(max_length=255)
    publish = models.DateTimeField(default=timezone.now)
    description = models.TextField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book:book_details', args=[
                        self.publish.year,
                        self.publish.month,
                        self.publish.day,
                        self.slug

                       ])

login/models.py
from django.db import models

# Create your models here.

book/forms.py
from django import forms
from .models import Book
from django.contrib.auth.forms import UserCreationForm
from  django import forms
from django.contrib.auth.models import User

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'author', 'description','publish',)

class UpdateBookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'author', 'description','publish',)



class SignUp(UserCreationForm):
    password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password1'}),
    )
    password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password2'}),
    )
    class Meta:
        model = User
        fields = ('username','password1', 'password2')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
        }

    def __init__(self, *args, **kwargs):
        super(SignUp, self).__init__(*args, **kwargs)
        for fieldname in self.fields:
            self.fields[fieldname].help_text = None

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        for fieldname in self.fields:
            self.fields[fieldname].help_text = None

class EmailForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    to = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    comments = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}))

login/forms.py
from django.contrib.auth.forms import UserCreationForm
from  django import forms
from django.contrib.auth.models import User
class SignUp(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

book/views.py
from django.shortcuts import render, get_object_or_404, redirect, HttpResponse

from config import settings
from .forms import BookForm, UpdateBookForm, SignUp, LoginForm, EmailForm
from .models import Book
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.views.generic import DetailView


@login_required
def books(request):
    books = Book.objects.all()
    users = User.objects.all()
    return render(request, 'book.html', {'books': books, 'users': users})


def user_books(request, username):
    user = get_object_or_404(User, username=username)
    books = Book.objects.filter(created_by=user)
    return render(request, 'user_books.html', {'books': books, 'user': user})


class BookList(DetailView):
    model = Book
    template_name = 'book_details.html'
    context_object_name = 'book'

    def get_object(self):
        year = self.kwargs['year']
        month = self.kwargs['month']
        day = self.kwargs['day']
        slug = self.kwargs['slug']

        return get_object_or_404(
            Book,
            status=Book.Status.PUBLISHED,
            slug=slug,
            publish__year=year,
            publish__month=month,
            publish__day=day
        )


def book_create(request):
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            book = form.save(commit=False)
            book.created_by = request.user
            form.save()
            return redirect('book:books')
    form = BookForm()
    return render(request, 'form.html', {'form': form})


def book_update(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        form = UpdateBookForm(request.POST, instance=book)
        if form.is_valid():
            form.save()
            return redirect('book:books')
    form = UpdateBookForm(instance=book)
    return render(request, 'form.html', {'form': form, 'book': book})


def delete(request, pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        book.delete()
        return redirect('book:books')
    return render(request, 'confirm.html', {'book': book})


def signup(request):
    if request.method == 'POST':
        form = SignUp(request.POST)
        if form.is_valid():
            form.save()
            return redirect('book:login')
    else:
        form = SignUp()
    return render(request, 'signup.html', {'form': form})


def home(request):
    return HttpResponse('<h1>Home Page</h1>')


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('book:book')
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})


def postdate(request):
    if request.method == 'POST':
        form = EmailForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            subject = f"This shared by {cd['name']}"
            # url = request.build_absolute_uri()
            massage = f"This massage sent by {cd['name']} - {cd['email']}'s comment's {cd['comments']}"
            send_mail(subject,
                      massage,
                      settings.EMAIL_HOST_USER, [cd['to']])
            return render(request, 'succes.html')
    else:
        form = EmailForm()
    return render(request, 'emailform.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('book:login')

login/views.py
from django.shortcuts import render,HttpResponse
from .forms import SignUp

def signup(request):
    if request.method == 'POST':
        form = SignUp(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse('<h1>You have successfully registered</h1>')
        else:
            form = SignUp()
        return render(request, 'signup.html', {'form': form})

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
            {% if user.is_authenticated %}
                <a class="navbar-brand" href="{% url 'book:book' %}">Welcome, {{ user.username }}</a>
            {% else %}
                <a class="navbar-brand" href="{% url 'book:book' %}">Welcome, Guest</a>
            {% endif %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'book:book' %}">Home</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'book:user_books' username=user.username %}">My books</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'book:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'book:login' %}?next={{ request.path }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'book:signup' %}">Sign Up</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% block content %}
{% endblock content %}


</body>
</html>

templates/book.html
{% extends 'base.html' %}
{% block content %}

    <div class="container">
    <h1>Library</h1>
    <a href="{% url 'book:book_create' %}" class="btn btn-primary add-book">Add Book</a>
    <ol>
        {% for book in books %}
        <li class="book-list">
            <div class="book-title"><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></div>
            <span class="created-by">Created by: {{ book.created_by.username }}</span>
            <a href="{% url 'book:send_email' %}" class="share-link">Share</a>
        </li>
        {% empty  %}
            <h2>No Post availeble</h2>
        {% endfor %}
    </ol>
</div>


{% endblock content %}

templates/book_details.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
        <h1>{{ book.title }}</h1>
        <p>{{ book.description }}</p>
        <p><strong>Author:</strong> {{ book.author }}</p>
        <p><strong>Publication Date:</strong> {{ book.year}}</p>
        <a href="{% url 'book:book' %}" class="btn btn-primary back-link">Back</a>
    </div>
    <script type="text/javascript" src="js/scripts.js"></script>
{% endblock content %}

templates/confirm.html
{% extends 'base.html' %}
{% block content %}


<div class="container">
        <h1>Are you sure you want to delete "{{ book.title }}"?</h1>
        <div class="btn-container">
            <form action="{% url 'book:delete' pk=book.pk %}" method="post">
                {% csrf_token %}
                <button class="btn btn-danger btn-yes" type="submit">Yes, I'm sure</button>
            </form>
            <form type="button"><a href="{% url 'book:books'  %}">
                <button class="btn btn-primary btn-no  "><a class="btn-no" href="{% url 'book:books'  %}">No, take me back</a></button>
            </form>
        </div>
    </div>
{% endblock content %}

templates/emailform.html
{% extends 'base.html' %}
{% block content %}

<h1>Sent email</h1>
<form method="post">
    {% csrf_token %}
    <div class="container">
        {{ form.as_p }}
        <button type="submit">Send email</button>
    </div>
</form>

{% endblock content %}

templates/form.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
        <h1>{% if book %}Update Book {% else %} Add Book{% endif %}</h1>
        <form action="{% if book %}{% url 'book:book_update' pk=book.pk %}{% else %}{% url 'book:book_create'%}{% endif %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_title">Title:</label>
                <input type="text" id="id_title" name="title" class="form-control" value="{% if book %} {{ book.title}} {% endif %}">
            </div>
            <div class="form-group">
                <label for="id_author">Author:</label>
                <input type="text" id="id_author" name="author" class="form-control" value="{% if book %} {{ book.author}} {% endif %}">
            </div>
            <div class="form-group">
                <label for="id_description">Description</label>
                <input type="text" id="id_description" name="description" class="form-control" value="{% if book %} {{ book.description}} {% endif %}">
            </div>
            <div class="form-group">
                <label for="id_published_date">Published Date:</label>
                <input type="date" id="id_published_date" name="year" class="form-control" value="{{ book.year|date:'Y-m-d' }}">
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

{% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% block content %}


    <div class="auth-container">
        <h1>Login</h1>
        <form method="post">
            {% csrf_token%}
            {{ form.as_p }}
            <button type="submit">Login </button>
        </form>
        <br>
        <a href="{% url 'book:signup' %}">Don't have an account</a>


    </div>
{% endblock content %}

templates/signup.html
{% extends 'base.html' %}
{% block content %}

    <div class="auth-container">
        <h1>Sign Up form</h1>
        <form method="post">
            {% csrf_token%}
            {{ form.as_p }}
            <button type="submit">Sign Up</button>
        </form>
        <br>
        <a href="{% url 'book:login' %}">Already have an account</a>

    </div>
{% endblock content %}

templates/succes.html
{% extends 'base.html' %}
{% block content %}
<br><br><br><br><br><br><br>
    <h1>Email sent successfully!</h1>

{% endblock content %}

templates/user_books.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
        <h1>{{ user.username }}'s Books</h1>
        <a href="{% url 'book:book_create' %}" class="btn btn-primary add-book">Add Book</a>
        <ol>
            {% for book in books %}
            <li class="book-list">
                <div class="book-title"><a href="">{{ book.title }}</a></div>
                <span class="created-by">Created by: {{ book.created_by.username }}</span>
                <div class="book-details">
                        <span class="book-actions">
                            <a href="{% url 'book:book_update' pk=book.pk %}">Update</a>
                            <a href="{% url 'book:delete' pk=book.pk %}">Delete</a>
                        </span>
                    </div>
            </li>
            {% endfor %}
        </ol>
    </div>


{% endblock content %}